<?php


namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Supply;
use App\Models\User;
use App\Models\Schedule;
use App\Models\Category;

class SupplySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    public function users() {
        return User::where('is_provider', true)->pluck('id');
    }

    public function schedules() {
        return Schedule::pluck('id');
    }

    public function run(): void
    {
        $users = $this->users();
        $schedules = $this->schedules();

        $supplies = [
            [
                'name' => 'Banquet Chair',
                'quantity' => 150,
                'price' => 100,
                'description' => 'Comfortable and elegant banquet chair with cushioned seat.',
                'is_service' => false,
                'address' => '123 Event Avenue, Party City',
                'experience' => 'Used in over 200 events for guests\' seating.',
                'img' => 'CHAIR/banquet-chair.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Furniture')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Goal chairs ',
                'quantity' => 300,
                'price' => 350,
                'description' => 'Comfortable and elegant banquet chair with cushioned seat.',
                'is_service' => false,
                'address' => '123 Event Avenue, Party City',
                'experience' => 'Used in over 200 events for guests\' seating.',
                'img' => 'CHAIR/goal-chairs.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Furniture')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Wooden Chair',
                'quantity' => 50,
                'price' => 45,
                'description' => 'Comfortable and elegant banquet chair with cushioned seat.',
                'is_service' => false,
                'address' => '123 Event Avenue, Party City',
                'experience' => 'Used in over 200 events for guests\' seating.',
                'img' => 'CHAIR/wooden-chairs.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Furniture')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Cube chairs',
                'quantity' => 45,
                'price' => 45,
                'description' => 'Comfortable and elegant banquet chair with cushioned seat.',
                'is_service' => false,
                'address' => '123 Event Avenue, Party City',
                'experience' => 'Used in over 200 events for guests\' seating.',
                'img' => 'CHAIR/cube-armchairs.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Furniture')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Classic chairs ',
                'quantity' => 500,
                'price' => 45,
                'description' => 'Comfortable and elegant banquet chair with cushioned seat.',
                'is_service' => false,
                'address' => '123 Event Avenue, Party City',
                'experience' => 'Used in over 200 events for guests\' seating.',
                'img' => 'CHAIR/classic-chairs.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Furniture')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Round Tables',
                'quantity' => 40,
                'price' => 120,
                'description' => 'Sturdy round table that seats up to 10 people.',
                'is_service' => false,
                'address' => '456 Celebration Street, Festival Town',
                'experience' => 'Popular choice for weddings and large gatherings.',
                'img' => 'TABLE/round-tables.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Furniture')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Square Tables',
                'quantity' => 35,
                'price' => 120,
                'description' => 'Sturdy round table that seats up to 10 people.',
                'is_service' => false,
                'address' => '456 Celebration Street, Festival Town',
                'experience' => 'Popular choice for weddings and large gatherings.',
                'img' => 'TABLE/square-tables.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Furniture')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Terrace Tables',
                'quantity' => 23,
                'price' => 120,
                'description' => 'Sturdy round table that seats up to 10 people.',
                'is_service' => false,
                'address' => '456 Celebration Street, Festival Town',
                'experience' => 'Popular choice for weddings and large gatherings.',
                'img' => 'TABLE/terrace-table.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Furniture')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'U-sharped Table',
                'quantity' => 20,
                'price' => 120,
                'description' => 'Sturdy round table that seats up to 10 people.',
                'is_service' => false,
                'address' => '456 Celebration Street, Festival Town',
                'experience' => 'Popular choice for weddings and large gatherings.',
                'img' => 'TABLE/U-shaped-table.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Furniture')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Oval Table',
                'quantity' => 55,
                'price' => 120,
                'description' => 'Sturdy round table that seats up to 10 people.',
                'is_service' => false,
                'address' => '456 Celebration Street, Festival Town',
                'experience' => 'Popular choice for weddings and large gatherings.',
                'img' => 'TABLE/oval-tables.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Furniture')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Stage Platform',
                'quantity' => 5,
                'price' => 500,
                'description' => 'Modular stage platform for performances and speeches.',
                'is_service' => false,
                'address' => '789 Performance Plaza, Showville',
                'experience' => 'Used in concerts and corporate events for better visibility.',
                'img' => 'STAGE/stage-plantform.webp',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Audiovisual equipment')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Color Lights ',
                'quantity' => 50,
                'price' => 1500,
                'description' => 'Professional lighting system for events.',
                'is_service' => false,
                'address' => '321 Bright Lane, Light City',
                'experience' => 'Provides atmospheric lighting for parties and performances.',
                'img' => 'LIGHT/color-lights.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Audiovisual equipment')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Laser Lightings',
                'quantity' => 700,
                'price' => 1500,
                'description' => 'Professional lighting system for events.',
                'is_service' => false,
                'address' => '321 Bright Lane, Light City',
                'experience' => 'Provides atmospheric lighting for parties and performances.',
                'img' => 'LIGHT/laser-lights.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Audiovisual equipment')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Proffesional Photographer',
                'quantity' => null,
                'price' => 80,
                'description' => 'Elegant flower arrangements for decor.',
                'is_service' => false,
                'address' => '987 Bloom Street, Garden City',
                'experience' => 'Adds beauty and elegance to any event.',
                'img' => 'ARRENGEMENT/professional-photographer.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Decoration')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Desserts Catering',
                'quantity' => 30,
                'price' => 200,
                'description' => 'Essential equipment for catering services.',
                'is_service' => false,
                'address' => '123 Serve Avenue, Chef City',
                'experience' => 'Used by professional caterers.',
                'img' => 'CATERI-E/desserts-catering.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Catering')->first(),
            ],
            [
                'name' => 'Plastic Catering',
                'quantity' => 20,
                'price' => 200,
                'description' => 'Essential equipment for catering services.',
                'is_service' => false,
                'address' => '123 Serve Avenue, Chef City',
                'experience' => 'Used by professional caterers.',
                'img' => 'CATERI-E/plastic-catering.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Catering')->first(),
                'schedule_id' => $schedules->random(),
                'category_id' => 1,
            ],
            [
                'name' => 'Small Catering',
                'quantity' => 15,
                'price' => 200,
                'description' => 'Essential equipment for catering services.',
                'is_service' => false,
                'address' => '123 Serve Avenue, Chef City',
                'experience' => 'Used by professional caterers.',
                'img' => 'CATERI-E/small-catering.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Catering')->first(),
                'schedule_id' => $schedules->random(),
                'category_id' => 1,
            ],
            [
                'name' => 'Waterfall Lighting',
                'quantity' => 500,
                'price' => 1500,
                'description' => 'Professional lighting system for events.',
                'is_service' => false,
                'address' => '321 Bright Lane, Light City',
                'experience' => 'Provides atmospheric lighting for parties and performances.',
                'img' => 'LIGHT/waterfall-lights.webp',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Audiovisual equipment')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Professional Florist',
                'quantity' => null,
                'price' => 80,
                'description' => 'Elegant flower arrangements for decor.',
                'is_service' => false,
                'address' => '987 Bloom Street, Garden City',
                'experience' => 'Adds beauty and elegance to any event.',
                'img' => 'ARRENGEMENT/professional-florist.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Decoration')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Lighting System',
                'quantity' => 25,
                'price' => 1500,
                'description' => 'Professional lighting system for events.',
                'is_service' => false,
                'address' => '321 Bright Lane, Light City',
                'experience' => 'Provides atmospheric lighting for parties and performances.',
                'img' => 'LIGHT/light-system.webp',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Audiovisual equipment')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Sound System',
                'quantity' => 8,
                'price' => 2000,
                'description' => 'High-quality sound system for clear audio at events.',
                'is_service' => true,
                'address' => '654 Audio Road, Music Town',
                'experience' => 'Ensures excellent sound quality for speeches, music, and presentations.',
                'img' => 'SOUND/sound-system.webp',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Audiovisual equipment')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Catering Service',
                'quantity' => null,
                'price' => 3000,
                'description' => 'Full catering service for events.',
                'is_service' => true,
                'address' => '987 Foodie Lane, Gourmet City',
                'experience' => 'Served over 500 events with gourmet food options.',
                'img' => 'CATERI-S/catering-service.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Catering')->first(),
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Small Catering Service',
                'quantity' => 35,
                'price' => 3000,
                'description' => 'Full catering service for events.',
                'is_service' => true,
                'address' => '987 Foodie Lane, Gourmet City',
                'experience' => 'Served over 500 events with gourmet food options.',
                'img' => 'CATERI-S/small-celebration.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Catering')->first(),
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Buffet Chef',
                'quantity' => null,
                'price' => 3000,
                'description' => 'Full catering service for events.',
                'is_service' => true,
                'address' => '987 Foodie Lane, Gourmet City',
                'experience' => 'Served over 500 events with gourmet food options.',
                'img' => 'CATERI-S/buffet-chef.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Catering')->first(),
                'schedule_id' => $schedules->random(),
            ],
            [ 'name' => 'Saucier Chef',
            'quantity' => null,
            'price' => 3000,
            'description' => 'Full catering service for events.',
            'is_service' => true,
            'address' => '987 Foodie Lane, Gourmet City',
            'experience' => 'Served over 500 events with gourmet food options.',
            'img' => 'CATERI-S/chef-saucier.jpg',
            'user_id' => $users->random(),
            'category_id' => Category::where('name', 'Catering')->first(),
            'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'large Speaker',
                'quantity' => 4,
                'price' => 2000,
                'description' => 'High-quality sound system for clear audio at events.',
                'is_service' => true,
                'address' => '654 Audio Road, Music Town',
                'experience' => 'Ensures excellent sound quality for speeches, music, and presentations.',
                'img' => 'SOUND/large-speaker.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Audiovisual equipment')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Medium Speaker',
                'quantity' => 7,
                'price' => 2000,
                'description' => 'High-quality sound system for clear audio at events.',
                'is_service' => true,
                'address' => '654 Audio Road, Music Town',
                'experience' => 'Ensures excellent sound quality for speeches, music, and presentations.',
                'img' => 'SOUND/medium-speaker.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Audiovisual equipment')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Small Speaker',
                'quantity' => 5,
                'price' => 2000,
                'description' => 'High-quality sound system for clear audio at events.',
                'is_service' => true,
                'address' => '654 Audio Road, Music Town',
                'experience' => 'Ensures excellent sound quality for speeches, music, and presentations.',
                'img' => 'SOUND/small-speaker.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Audiovisual equipment')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'DJ Service',
                'quantity' => null,
                'price' => 500,
                'description' => 'Professional DJ service for events.',
                'is_service' => true,
                'address' => '876 Music Avenue, Party Town',
                'experience' => 'Over 300 events with a diverse music collection.',
                'img' => 'DJ/dj-service.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Services')->first(),
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Decorative Lights',
                'quantity' => 50,
                'price' => 20,
                'description' => 'Beautiful decorative lights for ambiance.',
                'is_service' => false,
                'address' => '654 Illumination Street, Glow City',
                'experience' => 'Creates a magical atmosphere at events.',
                'img' => 'DECORATE/decorative-lights.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Audiovisual equipment')->first()->id,
                'schedule_id' => $schedules->random(),
            ],

            [
                'name' => 'Projector',
                'quantity' => 10,
                'price' => 350,
                'description' => 'High-resolution projector for presentations and events.',
                'is_service' => false,
                'address' => '432 Projection Drive, Visual City',
                'experience' => 'Used in various conferences and movie nights.',
                'img' => 'PROJECTOR/projector.webp',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Audiovisual equipment')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Dance Floor',
                'quantity' => 2,
                'price' => 700,
                'description' => 'Portable dance floor for events.',
                'is_service' => false,
                'address' => '210 Dance Street, Celebration City',
                'experience' => 'Perfect for weddings and parties.',
                'img' => 'FLOOR/dance-floor.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Furniture')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Complete Catering',
                'quantity' => 30,
                'price' => 200,
                'description' => 'Essential equipment for catering services.',
                'is_service' => false,
                'address' => '123 Serve Avenue, Chef City',
                'experience' => 'Used by professional caterers.',
                'img' => 'CATERI-E/complete-catering.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Catering')->first(),
                'schedule_id' => $schedules->random(),
                'category_id' => 1,
            ],
            [
                'name' => 'Photo Booth',
                'quantity' => 3,
                'price' => 450,
                'description' => 'Fun photo booth for event memories.',
                'is_service' => false,
                'address' => '321 Memory Lane, Snap City',
                'experience' => 'Captures unforgettable moments at events.',
                'img' => 'PHOTO/photo-booth.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Furniture')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Flower Arrangement',
                'quantity' => 100,
                'price' => 80,
                'description' => 'Elegant flower arrangements for decor.',
                'is_service' => false,
                'address' => '987 Bloom Street, Garden City',
                'experience' => 'Adds beauty and elegance to any event.',
                'img' => 'ARRENGEMENT/flower-arrangement.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Decoration')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Catering Equipment',
                'quantity' => 30,
                'price' => 200,
                'description' => 'Essential equipment for catering services.',
                'is_service' => false,
                'address' => '123 Serve Avenue, Chef City',
                'experience' => 'Used by professional caterers.',
                'img' => 'CATERI-E/catering-equipment.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Catering')->first(),
                'schedule_id' => $schedules->random(),
                'category_id' => 1,
            ],

            //$supplies->save(),
            [
                'name' => 'Security Service',
                'quantity' => null,
                'price' => 1000,
                'description' => 'Professional security services for events.',
                'is_service' => true,
                'address' => '789 Safety Boulevard, Secure City',
                'experience' => 'Ensures safety and security at events.',
                'img' => 'SECURITY-S/security.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Services')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Elegant Ballroom',
                'quantity' => 1,
                'price' => 5000,
                'description' => 'Spacious and luxurious ballroom for grand events and weddings.',
                'is_service' => true,
                'address' => '123 Grandeur Avenue, Luxe City',
                'experience' => 'Hosted over 500 high-profile events and weddings.',
                'img' => '',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Venue')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Rustic Barn Venue',
                'quantity' => 1,
                'price' => 3000,
                'description' => 'Charming rustic barn perfect for country-themed weddings and events.',
                'is_service' => true,
                'address' => '456 Countryside Lane, Rural County',
                'experience' => 'Featured in multiple wedding magazines for its unique ambiance.',
                'img' => '',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Venue')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Beachfront Event Space',
                'quantity' => 1,
                'price' => 4000,
                'description' => 'Stunning beachfront location for memorable seaside events.',
                'is_service' => true,
                'address' => '789 Ocean Drive, Coastal Town',
                'experience' => 'Hosted numerous beach weddings and corporate retreats.',
                'img' => '',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Venue')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Modern Loft Space',
                'quantity' => 1,
                'price' => 2500,
                'description' => 'Sleek and contemporary loft space ideal for artistic events and photo shoots.',
                'is_service' => true,
                'address' => '101 Urban Street, Metropolitan City',
                'experience' => 'Popular among fashion designers and tech startups for launch events.',
                'img' => '',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Venue')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Garden Pavilion',
                'quantity' => 1,
                'price' => 3500,
                'description' => 'Enchanting garden pavilion surrounded by lush greenery and flowers.',
                'is_service' => true,
                'address' => '222 Botanical Way, Green Acres',
                'experience' => 'Ideal for spring and summer outdoor events and ceremonies.',
                'img' => '',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Venue')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Historic Mansion',
                'quantity' => 1,
                'price' => 6000,
                'description' => 'Elegant 19th-century mansion with ornate architecture and sprawling grounds.',
                'is_service' => true,
                'address' => '333 Heritage Road, Old Town',
                'experience' => 'Hosted several high-profile charity galas and period film productions.',
                'img' => 'VENUES/historic-mansion.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Venue')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Rooftop Terrace',
                'quantity' => 1,
                'price' => 3000,
                'description' => 'Stunning rooftop venue with panoramic city views.',
                'is_service' => true,
                'address' => '444 Skyline Boulevard, Downtown',
                'experience' => 'Popular for cocktail parties and intimate wedding receptions.',
                'img' => 'VENUES/rooftop-terrace.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Venue')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Vineyard Estate',
                'quantity' => 1,
                'price' => 5500,
                'description' => 'Picturesque vineyard setting with indoor and outdoor event spaces.',
                'is_service' => true,
                'address' => '555 Grape Lane, Wine Country',
                'experience' => 'Renowned for destination weddings and wine-tasting events.',
                'img' => 'VENUES/vineyard-estate.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Venue')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Industrial Warehouse',
                'quantity' => 1,
                'price' => 2000,
                'description' => 'Versatile industrial space perfect for edgy events and large gatherings.',
                'is_service' => true,
                'address' => '666 Factory Row, Warehouse District',
                'experience' => 'Hosted music festivals, art exhibitions, and tech conferences.',
                'img' => 'VENUES/industrial-warehouse.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Venue')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
            [
                'name' => 'Mountain Lodge',
                'quantity' => 1,
                'price' => 4500,
                'description' => 'Cozy mountain retreat with stunning natural surroundings.',
                'is_service' => true,
                'address' => '777 Alpine Way, Mountain Vista',
                'experience' => 'Ideal for corporate retreats and winter wonderland weddings.',
                'img' => 'VENUES/mountain-lodge.jpg',
                'user_id' => $users->random(),
                'category_id' => Category::where('name', 'Venue')->first()->id,
                'schedule_id' => $schedules->random(),
            ],
        ];

        Supply::factory(count($supplies))->sequence(fn ($sqn) => $supplies[$sqn->index])->create();

    }
}
